"""empty message

Revision ID: 4c509ae0f391
Revises: None
Create Date: 2014-09-18 10:18:11.128018

"""

# revision identifiers, used by Alembic.
revision = '4c509ae0f391'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
